GET http://localhost:3000/api/clientes

###
GET http://localhost:3000/api/clientes/23232

###
POST  http://localhost:3000/api/clientes
Content-Type: application/json

{
  "nombre": "Maria",
  "apellidos": "Romero",
  "direccion": "Calle Falsa, 123",
  "email": "maria.romero@example.com",
  "edad": 37,
  "genero": "F",
  "cuota": 9.90,
  "fecha_nacimiento": "1987-06-15",
  "dni": "12545612R"
}

###
PUT  http://localhost:3000/api/clientes/234
Content-Type: application/json

{
  "nombre": "Maria",
  "apellidos": "Romero",
  "direccion": "Calle Falsa, 123",
  "email": "maria.romero@example.com",
  "edad": 37,
  "genero": "M",
  "cuota": 9.90,
  "fecha_nacimiento": "1987-06-15",
  "dni": "12545612R"
}


###
DELETE  http://localhost:3000/api/clientes/19
